/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Marco' at '02.12.16 09:13' with Gradle 3.0
 *
 * @author Marco, @date 02.12.16 09:13
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
