/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Marco' at '25.11.16 16:17' with Gradle 3.0
 *
 * @author Marco, @date 25.11.16 16:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
